import { AppNotification, Clan, CollectivePrediction, FeedPost, Match, Mission, PowerUp, Tipster, User } from './nexaStore';

// ─── Matches ──────────────────────────────────────────────────────────────────

export const MOCK_MATCHES: Match[] = [
  // ── Ao Vivo ────────────────────────────────────────────────────────────────
  {
    id: 'match1',
    league: 'Brasileirão Série A',
    homeTeam: 'Flamengo',
    awayTeam: 'Corinthians',
    status: 'live',
    minute: 67,
    score: { home: 1, away: 0 },
    odds: { home: 1.45, draw: 3.80, away: 6.50 },
    bettors: 2470,
    trending: true,
    oddsMovement: { home: -1, draw: 0, away: 1 }, // Fla winning, home odds falling
  },
  {
    id: 'match5',
    league: 'Serie A',
    homeTeam: 'Napoli',
    awayTeam: 'Roma',
    status: 'live',
    minute: 34,
    score: { home: 0, away: 0 },
    odds: { home: 2.05, draw: 3.30, away: 3.60 },
    bettors: 1820,
    trending: false,
    oddsMovement: { home: 0, draw: -1, away: 1 },
  },
  {
    id: 'match6',
    league: 'Ligue 1',
    homeTeam: 'PSG',
    awayTeam: 'Lyon',
    status: 'live',
    minute: 81,
    score: { home: 2, away: 1 },
    odds: { home: 1.28, draw: 5.50, away: 9.00 },
    bettors: 3140,
    trending: true,
    oddsMovement: { home: -1, draw: 0, away: 1 }, // PSG dominating
  },
  {
    id: 'match13',
    league: 'Premier League',
    homeTeam: 'Manchester United',
    awayTeam: 'Chelsea',
    status: 'live',
    minute: 22,
    score: { home: 0, away: 1 },
    odds: { home: 3.40, draw: 3.20, away: 2.10 },
    bettors: 4580,
    trending: true,
    oddsMovement: { home: 1, draw: 0, away: -1 },
  },
  {
    id: 'match14',
    league: 'Brasileirão Série A',
    homeTeam: 'Internacional',
    awayTeam: 'Cruzeiro',
    status: 'live',
    minute: 55,
    score: { home: 2, away: 2 },
    odds: { home: 2.80, draw: 2.60, away: 3.10 },
    bettors: 1950,
    trending: false,
    oddsMovement: { home: 0, draw: -1, away: 0 },
  },
  {
    id: 'match15',
    league: 'La Liga',
    homeTeam: 'Sevilla',
    awayTeam: 'Real Betis',
    status: 'live',
    minute: 72,
    score: { home: 1, away: 0 },
    odds: { home: 1.55, draw: 4.00, away: 5.80 },
    bettors: 1340,
    trending: false,
    oddsMovement: { home: -1, draw: 0, away: 1 },
  },
  {
    id: 'match16',
    league: 'Bundesliga',
    homeTeam: 'Bayern Munich',
    awayTeam: 'Bayer Leverkusen',
    status: 'live',
    minute: 45,
    score: { home: 1, away: 1 },
    odds: { home: 2.00, draw: 3.20, away: 3.80 },
    bettors: 3720,
    trending: true,
    oddsMovement: { home: 0, draw: -1, away: 0 },
  },

  // ── Hoje ───────────────────────────────────────────────────────────────────
  {
    id: 'match2',
    league: 'Premier League',
    homeTeam: 'Arsenal',
    awayTeam: 'Liverpool',
    status: 'pre',
    odds: { home: 2.10, draw: 3.40, away: 1.85 },
    bettors: 5830,
    trending: true,
    scheduledDay: 'today',
    scheduledTime: '15:30',
    oddsMovement: { home: 0, draw: 0, away: -1 }, // Liverpool money flowing
  },
  {
    id: 'match3',
    league: 'UEFA Champions League',
    homeTeam: 'Real Madrid',
    awayTeam: 'Bayern Munich',
    status: 'pre',
    odds: { home: 1.95, draw: 3.60, away: 2.20 },
    bettors: 8920,
    trending: true,
    scheduledDay: 'today',
    scheduledTime: '21:00',
    oddsMovement: { home: -1, draw: 0, away: 1 }, // Real Madrid popular
  },
  {
    id: 'match7',
    league: 'Brasileirão Série A',
    homeTeam: 'Palmeiras',
    awayTeam: 'São Paulo',
    status: 'pre',
    odds: { home: 1.80, draw: 3.20, away: 4.50 },
    bettors: 4200,
    trending: true,
    scheduledDay: 'today',
    scheduledTime: '19:00',
    oddsMovement: { home: -1, draw: 0, away: 0 },
  },
  {
    id: 'match8',
    league: 'La Liga',
    homeTeam: 'Real Sociedad',
    awayTeam: 'Villarreal',
    status: 'pre',
    odds: { home: 2.30, draw: 3.10, away: 3.20 },
    bettors: 920,
    trending: false,
    scheduledDay: 'today',
    scheduledTime: '17:00',
  },
  {
    id: 'match17',
    league: 'Brasileirão Série A',
    homeTeam: 'Botafogo',
    awayTeam: 'Fluminense',
    status: 'pre',
    odds: { home: 1.90, draw: 3.30, away: 4.20 },
    bettors: 3680,
    trending: true,
    scheduledDay: 'today',
    scheduledTime: '16:00',
    oddsMovement: { home: -1, draw: 0, away: 1 },
  },
  {
    id: 'match18',
    league: 'Premier League',
    homeTeam: 'Tottenham',
    awayTeam: 'Newcastle',
    status: 'pre',
    odds: { home: 2.40, draw: 3.30, away: 2.90 },
    bettors: 2940,
    trending: false,
    scheduledDay: 'today',
    scheduledTime: '13:00',
  },
  {
    id: 'match19',
    league: 'La Liga',
    homeTeam: 'Athletic Bilbao',
    awayTeam: 'Valencia',
    status: 'pre',
    odds: { home: 1.75, draw: 3.40, away: 4.80 },
    bettors: 1120,
    trending: false,
    scheduledDay: 'today',
    scheduledTime: '14:00',
  },
  {
    id: 'match20',
    league: 'Serie A',
    homeTeam: 'AC Milan',
    awayTeam: 'Atalanta',
    status: 'pre',
    odds: { home: 2.15, draw: 3.25, away: 3.40 },
    bettors: 2450,
    trending: false,
    scheduledDay: 'today',
    scheduledTime: '15:45',
    oddsMovement: { home: 0, draw: 0, away: -1 },
  },
  {
    id: 'match21',
    league: 'UEFA Champions League',
    homeTeam: 'Barcelona',
    awayTeam: 'Inter Milan',
    status: 'pre',
    odds: { home: 1.60, draw: 3.90, away: 5.00 },
    bettors: 7400,
    trending: true,
    scheduledDay: 'today',
    scheduledTime: '21:00',
    oddsMovement: { home: -1, draw: 0, away: 1 },
  },
  {
    id: 'match22',
    league: 'Bundesliga',
    homeTeam: 'Wolfsburg',
    awayTeam: 'Freiburg',
    status: 'pre',
    odds: { home: 2.20, draw: 3.20, away: 3.30 },
    bettors: 780,
    trending: false,
    scheduledDay: 'today',
    scheduledTime: '16:30',
  },
  {
    id: 'match23',
    league: 'Brasileirão Série A',
    homeTeam: 'Santos',
    awayTeam: 'Bahia',
    status: 'pre',
    odds: { home: 2.00, draw: 3.15, away: 3.80 },
    bettors: 1640,
    trending: false,
    scheduledDay: 'today',
    scheduledTime: '18:30',
  },
  {
    id: 'match24',
    league: 'Ligue 1',
    homeTeam: 'Marseille',
    awayTeam: 'Monaco',
    status: 'pre',
    odds: { home: 2.25, draw: 3.30, away: 3.10 },
    bettors: 1980,
    trending: false,
    scheduledDay: 'today',
    scheduledTime: '21:00',
  },
  {
    id: 'match25',
    league: 'Copa Libertadores',
    homeTeam: 'River Plate',
    awayTeam: 'Flamengo',
    status: 'pre',
    odds: { home: 2.30, draw: 3.10, away: 2.80 },
    bettors: 6200,
    trending: true,
    scheduledDay: 'today',
    scheduledTime: '21:30',
    oddsMovement: { home: 0, draw: 0, away: -1 },
  },

  // ── Amanhã ─────────────────────────────────────────────────────────────────
  {
    id: 'match9',
    league: 'UEFA Champions League',
    homeTeam: 'Manchester City',
    awayTeam: 'PSG',
    status: 'pre',
    odds: { home: 1.70, draw: 3.80, away: 4.80 },
    bettors: 11200,
    trending: true,
    scheduledDay: 'tomorrow',
    scheduledTime: '21:00',
    oddsMovement: { home: -1, draw: 0, away: 1 },
  },
  {
    id: 'match10',
    league: 'Serie A',
    homeTeam: 'Juventus',
    awayTeam: 'Inter Milan',
    status: 'pre',
    odds: { home: 2.20, draw: 3.25, away: 3.10 },
    bettors: 6540,
    trending: true,
    scheduledDay: 'tomorrow',
    scheduledTime: '18:45',
  },
  {
    id: 'match11',
    league: 'Bundesliga',
    homeTeam: 'Borussia Dortmund',
    awayTeam: 'RB Leipzig',
    status: 'pre',
    odds: { home: 2.05, draw: 3.40, away: 3.50 },
    bettors: 3870,
    trending: false,
    scheduledDay: 'tomorrow',
    scheduledTime: '16:30',
  },
  {
    id: 'match12',
    league: 'Brasileirão Série A',
    homeTeam: 'Atlético Mineiro',
    awayTeam: 'Grêmio',
    status: 'pre',
    odds: { home: 1.65, draw: 3.50, away: 5.20 },
    bettors: 2140,
    trending: false,
    scheduledDay: 'tomorrow',
    scheduledTime: '20:00',
  },
  {
    id: 'match26',
    league: 'Premier League',
    homeTeam: 'Aston Villa',
    awayTeam: 'West Ham',
    status: 'pre',
    odds: { home: 1.85, draw: 3.40, away: 4.20 },
    bettors: 1920,
    trending: false,
    scheduledDay: 'tomorrow',
    scheduledTime: '15:00',
  },
  {
    id: 'match27',
    league: 'La Liga',
    homeTeam: 'Atlético Madrid',
    awayTeam: 'Real Madrid',
    status: 'pre',
    odds: { home: 2.80, draw: 3.10, away: 2.50 },
    bettors: 9300,
    trending: true,
    scheduledDay: 'tomorrow',
    scheduledTime: '21:00',
    oddsMovement: { home: 1, draw: 0, away: -1 },
  },
  {
    id: 'match28',
    league: 'Brasileirão Série A',
    homeTeam: 'Vasco',
    awayTeam: 'Fortaleza',
    status: 'pre',
    odds: { home: 2.60, draw: 3.00, away: 2.85 },
    bettors: 1780,
    trending: false,
    scheduledDay: 'tomorrow',
    scheduledTime: '19:00',
  },
  {
    id: 'match29',
    league: 'Serie A',
    homeTeam: 'Lazio',
    awayTeam: 'Fiorentina',
    status: 'pre',
    odds: { home: 2.10, draw: 3.20, away: 3.50 },
    bettors: 1350,
    trending: false,
    scheduledDay: 'tomorrow',
    scheduledTime: '15:00',
  },
  {
    id: 'match30',
    league: 'Bundesliga',
    homeTeam: 'Eintracht Frankfurt',
    awayTeam: 'Stuttgart',
    status: 'pre',
    odds: { home: 2.15, draw: 3.30, away: 3.40 },
    bettors: 1190,
    trending: false,
    scheduledDay: 'tomorrow',
    scheduledTime: '16:30',
  },
  {
    id: 'match31',
    league: 'Premier League',
    homeTeam: 'Brighton',
    awayTeam: 'Everton',
    status: 'pre',
    odds: { home: 1.60, draw: 3.70, away: 5.50 },
    bettors: 1440,
    trending: false,
    scheduledDay: 'tomorrow',
    scheduledTime: '13:30',
  },
  {
    id: 'match32',
    league: 'La Liga',
    homeTeam: 'Girona',
    awayTeam: 'Celta Vigo',
    status: 'pre',
    odds: { home: 1.90, draw: 3.30, away: 4.10 },
    bettors: 720,
    trending: false,
    scheduledDay: 'tomorrow',
    scheduledTime: '14:00',
  },
  {
    id: 'match33',
    league: 'Copa Libertadores',
    homeTeam: 'Boca Juniors',
    awayTeam: 'Palmeiras',
    status: 'pre',
    odds: { home: 2.40, draw: 3.00, away: 2.90 },
    bettors: 5800,
    trending: true,
    scheduledDay: 'tomorrow',
    scheduledTime: '21:30',
    oddsMovement: { home: -1, draw: 0, away: 1 },
  },
  {
    id: 'match34',
    league: 'UEFA Champions League',
    homeTeam: 'Borussia Dortmund',
    awayTeam: 'Atlético Madrid',
    status: 'pre',
    odds: { home: 2.10, draw: 3.40, away: 3.30 },
    bettors: 4100,
    trending: false,
    scheduledDay: 'tomorrow',
    scheduledTime: '21:00',
  },
  {
    id: 'match35',
    league: 'Brasileirão Série A',
    homeTeam: 'Corinthians',
    awayTeam: 'Athletico-PR',
    status: 'pre',
    odds: { home: 1.95, draw: 3.20, away: 3.90 },
    bettors: 2650,
    trending: false,
    scheduledDay: 'tomorrow',
    scheduledTime: '16:00',
  },
  {
    id: 'match36',
    league: 'Ligue 1',
    homeTeam: 'Lille',
    awayTeam: 'Nice',
    status: 'pre',
    odds: { home: 2.00, draw: 3.25, away: 3.70 },
    bettors: 890,
    trending: false,
    scheduledDay: 'tomorrow',
    scheduledTime: '17:00',
  },

  // ── Encerrado (para resultado em posts) ────────────────────────────────────
  {
    id: 'match4',
    league: 'La Liga',
    homeTeam: 'Barcelona',
    awayTeam: 'Atlético Madrid',
    status: 'finished',
    score: { home: 2, away: 1 },
    odds: { home: 1.72, draw: 3.50, away: 4.20 },
    bettors: 4110,
    trending: false,
  },
  {
    id: 'match37',
    league: 'Brasileirão Série A',
    homeTeam: 'Palmeiras',
    awayTeam: 'Flamengo',
    status: 'finished',
    score: { home: 0, away: 0 },
    odds: { home: 1.85, draw: 3.30, away: 4.00 },
    bettors: 5200,
    trending: false,
  },
  {
    id: 'match38',
    league: 'Premier League',
    homeTeam: 'Liverpool',
    awayTeam: 'Manchester City',
    status: 'finished',
    score: { home: 3, away: 1 },
    odds: { home: 2.00, draw: 3.40, away: 3.50 },
    bettors: 8100,
    trending: false,
  },
  {
    id: 'match39',
    league: 'Serie A',
    homeTeam: 'Inter Milan',
    awayTeam: 'AC Milan',
    status: 'finished',
    score: { home: 2, away: 0 },
    odds: { home: 1.65, draw: 3.60, away: 5.00 },
    bettors: 4800,
    trending: false,
  },
  {
    id: 'match40',
    league: 'Bundesliga',
    homeTeam: 'Borussia Dortmund',
    awayTeam: 'Bayern Munich',
    status: 'finished',
    score: { home: 1, away: 3 },
    odds: { home: 3.10, draw: 3.40, away: 2.15 },
    bettors: 6300,
    trending: false,
  },
  {
    id: 'match41',
    league: 'La Liga',
    homeTeam: 'Real Madrid',
    awayTeam: 'Sevilla',
    status: 'finished',
    score: { home: 4, away: 0 },
    odds: { home: 1.35, draw: 4.80, away: 8.00 },
    bettors: 3900,
    trending: false,
  },
  {
    id: 'match42',
    league: 'UEFA Champions League',
    homeTeam: 'Liverpool',
    awayTeam: 'Barcelona',
    status: 'finished',
    score: { home: 2, away: 2 },
    odds: { home: 2.20, draw: 3.40, away: 3.10 },
    bettors: 9800,
    trending: false,
  },
  {
    id: 'match43',
    league: 'Brasileirão Série A',
    homeTeam: 'São Paulo',
    awayTeam: 'Botafogo',
    status: 'finished',
    score: { home: 1, away: 2 },
    odds: { home: 2.10, draw: 3.20, away: 3.50 },
    bettors: 2800,
    trending: false,
  },
  {
    id: 'match44',
    league: 'Copa Libertadores',
    homeTeam: 'Flamengo',
    awayTeam: 'Boca Juniors',
    status: 'finished',
    score: { home: 3, away: 1 },
    odds: { home: 1.80, draw: 3.40, away: 4.20 },
    bettors: 7600,
    trending: false,
  },
  {
    id: 'match45',
    league: 'Premier League',
    homeTeam: 'Chelsea',
    awayTeam: 'Arsenal',
    status: 'finished',
    score: { home: 0, away: 1 },
    odds: { home: 2.70, draw: 3.20, away: 2.60 },
    bettors: 5400,
    trending: false,
  },
  {
    id: 'match46',
    league: 'Ligue 1',
    homeTeam: 'PSG',
    awayTeam: 'Marseille',
    status: 'finished',
    score: { home: 2, away: 0 },
    odds: { home: 1.40, draw: 4.50, away: 7.00 },
    bettors: 3200,
    trending: false,
  },
  {
    id: 'match47',
    league: 'Copa Libertadores',
    homeTeam: 'Atlético Mineiro',
    awayTeam: 'River Plate',
    status: 'finished',
    score: { home: 1, away: 1 },
    odds: { home: 2.50, draw: 3.10, away: 2.80 },
    bettors: 4300,
    trending: false,
  },
  {
    id: 'match48',
    league: 'Bundesliga',
    homeTeam: 'RB Leipzig',
    awayTeam: 'Wolfsburg',
    status: 'finished',
    score: { home: 2, away: 1 },
    odds: { home: 1.70, draw: 3.60, away: 4.80 },
    bettors: 1600,
    trending: false,
  },
  {
    id: 'match49',
    league: 'Serie A',
    homeTeam: 'Roma',
    awayTeam: 'Juventus',
    status: 'finished',
    score: { home: 0, away: 1 },
    odds: { home: 2.90, draw: 3.10, away: 2.50 },
    bettors: 3500,
    trending: false,
  },
  {
    id: 'match50',
    league: 'Brasileirão Série A',
    homeTeam: 'Grêmio',
    awayTeam: 'Internacional',
    status: 'finished',
    score: { home: 2, away: 1 },
    odds: { home: 2.30, draw: 3.00, away: 3.20 },
    bettors: 4600,
    trending: false,
  },
  // ── Libertadores ────────────────────────────────────────────────────────
  { id: 'match51', league: 'Libertadores', homeTeam: 'Boca Juniors', awayTeam: 'River Plate', status: 'live', minute: 72, score: { home: 1, away: 1 }, odds: { home: 2.40, draw: 3.10, away: 2.80 }, bettors: 14200, trending: true, oddsMovement: { home: 0, draw: -1, away: 0 } },
  { id: 'match52', league: 'Libertadores', homeTeam: 'Fluminense', awayTeam: 'Cerro Porteño', status: 'pre', odds: { home: 1.55, draw: 3.80, away: 5.40 }, bettors: 3800, trending: false, scheduledDay: 'today', scheduledTime: '21:30' },
  { id: 'match53', league: 'Libertadores', homeTeam: 'Peñarol', awayTeam: 'Nacional', status: 'pre', odds: { home: 2.10, draw: 3.20, away: 3.40 }, bettors: 2100, trending: false, scheduledDay: 'tomorrow', scheduledTime: '19:15' },
  { id: 'match54', league: 'Libertadores', homeTeam: 'Palmeiras', awayTeam: 'Boca Juniors', status: 'finished', score: { home: 3, away: 1 }, odds: { home: 1.65, draw: 3.50, away: 5.00 }, bettors: 9800, trending: true },
  { id: 'match55', league: 'Libertadores', homeTeam: 'River Plate', awayTeam: 'Atlético Mineiro', status: 'finished', score: { home: 0, away: 2 }, odds: { home: 2.20, draw: 3.30, away: 3.10 }, bettors: 7400, trending: false },
  // ── Premier League extra ────────────────────────────────────────────────
  { id: 'match56', league: 'Premier League', homeTeam: 'Manchester United', awayTeam: 'Chelsea', status: 'pre', odds: { home: 2.50, draw: 3.20, away: 2.80 }, bettors: 8900, trending: true, scheduledDay: 'today', scheduledTime: '13:30', oddsMovement: { home: 1, draw: 0, away: -1 } },
  { id: 'match57', league: 'Premier League', homeTeam: 'Tottenham', awayTeam: 'Newcastle', status: 'pre', odds: { home: 2.20, draw: 3.40, away: 3.10 }, bettors: 5200, trending: false, scheduledDay: 'today', scheduledTime: '16:00' },
  { id: 'match58', league: 'Premier League', homeTeam: 'Aston Villa', awayTeam: 'Brighton', status: 'pre', odds: { home: 1.90, draw: 3.50, away: 3.80 }, bettors: 3100, trending: false, scheduledDay: 'tomorrow', scheduledTime: '15:00' },
  { id: 'match59', league: 'Premier League', homeTeam: 'Chelsea', awayTeam: 'Arsenal', status: 'finished', score: { home: 1, away: 2 }, odds: { home: 2.60, draw: 3.20, away: 2.70 }, bettors: 11000, trending: true },
  // ── Copa do Brasil ──────────────────────────────────────────────────────
  { id: 'match60', league: 'Copa do Brasil', homeTeam: 'Flamengo', awayTeam: 'Cruzeiro', status: 'live', minute: 45, score: { home: 2, away: 0 }, odds: { home: 1.18, draw: 6.50, away: 14.0 }, bettors: 6700, trending: true, oddsMovement: { home: -1, draw: 0, away: 1 } },
  { id: 'match61', league: 'Copa do Brasil', homeTeam: 'Vasco', awayTeam: 'Corinthians', status: 'pre', odds: { home: 2.30, draw: 3.10, away: 3.00 }, bettors: 4500, trending: false, scheduledDay: 'today', scheduledTime: '20:00' },
  { id: 'match62', league: 'Copa do Brasil', homeTeam: 'Cruzeiro', awayTeam: 'Palmeiras', status: 'finished', score: { home: 0, away: 1 }, odds: { home: 2.80, draw: 3.00, away: 2.60 }, bettors: 5200, trending: false },
  // ── Bundesliga extra ────────────────────────────────────────────────────
  { id: 'match63', league: 'Bundesliga', homeTeam: 'Bayern Munich', awayTeam: 'Bayer Leverkusen', status: 'pre', odds: { home: 1.75, draw: 3.80, away: 4.20 }, bettors: 7800, trending: true, scheduledDay: 'tomorrow', scheduledTime: '16:30', oddsMovement: { home: -1, draw: 0, away: 1 } },
  { id: 'match64', league: 'Bundesliga', homeTeam: 'Stuttgart', awayTeam: 'Freiburg', status: 'pre', odds: { home: 2.10, draw: 3.30, away: 3.40 }, bettors: 1800, trending: false, scheduledDay: 'tomorrow', scheduledTime: '14:30' },
  // ── Serie A Italy extra ─────────────────────────────────────────────────
  { id: 'match65', league: 'Serie A', homeTeam: 'AC Milan', awayTeam: 'Atalanta', status: 'pre', odds: { home: 2.05, draw: 3.30, away: 3.50 }, bettors: 4200, trending: false, scheduledDay: 'today', scheduledTime: '18:00' },
  { id: 'match66', league: 'Serie A', homeTeam: 'Lazio', awayTeam: 'Fiorentina', status: 'finished', score: { home: 3, away: 2 }, odds: { home: 2.20, draw: 3.20, away: 3.30 }, bettors: 2900, trending: false },
  // ── Eredivisie ──────────────────────────────────────────────────────────
  { id: 'match67', league: 'Eredivisie', homeTeam: 'Ajax', awayTeam: 'PSV', status: 'pre', odds: { home: 2.40, draw: 3.30, away: 2.80 }, bettors: 3400, trending: true, scheduledDay: 'tomorrow', scheduledTime: '17:00' },
  // ── Liga Portugal ───────────────────────────────────────────────────────
  { id: 'match68', league: 'Liga Portugal', homeTeam: 'Benfica', awayTeam: 'Porto', status: 'pre', odds: { home: 2.10, draw: 3.20, away: 3.40 }, bettors: 5100, trending: true, scheduledDay: 'today', scheduledTime: '19:30', oddsMovement: { home: -1, draw: 0, away: 1 } },
  // ── Ligue 1 extra ───────────────────────────────────────────────────────
  { id: 'match69', league: 'Ligue 1', homeTeam: 'Marseille', awayTeam: 'Monaco', status: 'live', minute: 55, score: { home: 1, away: 0 }, odds: { home: 1.60, draw: 3.80, away: 5.00 }, bettors: 2600, trending: false },
  { id: 'match70', league: 'Ligue 1', homeTeam: 'Lille', awayTeam: 'Nice', status: 'finished', score: { home: 2, away: 2 }, odds: { home: 2.00, draw: 3.40, away: 3.60 }, bettors: 1500, trending: false },
];

// ─── Tipsters ─────────────────────────────────────────────────────────────────

export const MOCK_TIPSTERS: Tipster[] = [
  {
    id: 't1',
    username: 'KingBet',
    avatar: '',
    winRate: 0.68,
    roi: 0.24,
    followers: 12400,
    streak: 7,
    tier: 'elite',
    isFollowing: false,
    recentPick: { matchId: 'match3', side: 'home', odds: 1.95 },
  },
  {
    id: 't2',
    username: 'StatMaster',
    avatar: '',
    winRate: 0.61,
    roi: 0.15,
    followers: 8240,
    streak: 4,
    tier: 'gold',
    isFollowing: true,
    recentPick: { matchId: 'match2', side: 'away', odds: 1.85 },
  },
  {
    id: 't3',
    username: 'ValueHunt',
    avatar: '',
    winRate: 0.58,
    roi: 0.19,
    followers: 5180,
    streak: 3,
    tier: 'gold',
    isFollowing: false,
    recentPick: { matchId: 'match1', side: 'home', odds: 1.45 },
  },
  {
    id: 't4',
    username: 'GoalGuru',
    avatar: '',
    winRate: 0.54,
    roi: 0.08,
    followers: 3310,
    streak: 2,
    tier: 'silver',
    isFollowing: false,
  },
  {
    id: 't5',
    username: 'AcePredict',
    avatar: '',
    winRate: 0.72,
    roi: 0.31,
    followers: 21000,
    streak: 11,
    tier: 'elite',
    isFollowing: true,
    recentPick: { matchId: 'match2', side: 'home', odds: 2.10 },
  },
  {
    id: 't6',
    username: 'OddsBreaker',
    avatar: '',
    winRate: 0.56,
    roi: 0.12,
    followers: 1890,
    streak: 1,
    tier: 'silver',
    isFollowing: false,
    recentPick: { matchId: 'match9', side: 'home', odds: 1.70 },
  },
  // ── Elite ──────────────────────────────────────────────────────────────────
  {
    id: 't7',
    username: 'BrazilKing',
    avatar: '',
    winRate: 0.70,
    roi: 0.28,
    followers: 18500,
    streak: 9,
    tier: 'elite',
    isFollowing: false,
    recentPick: { matchId: 'match7', side: 'home', odds: 1.80 },
  },
  {
    id: 't8',
    username: 'ProSniper',
    avatar: '',
    winRate: 0.75,
    roi: 0.35,
    followers: 24800,
    streak: 12,
    tier: 'elite',
    isFollowing: false,
    recentPick: { matchId: 'match21', side: 'home', odds: 1.60 },
  },
  // ── Gold ───────────────────────────────────────────────────────────────────
  {
    id: 't9',
    username: 'DrawMaster',
    avatar: '',
    winRate: 0.59,
    roi: 0.17,
    followers: 6700,
    streak: 5,
    tier: 'gold',
    isFollowing: false,
    recentPick: { matchId: 'match27', side: 'draw', odds: 3.10 },
  },
  {
    id: 't10',
    username: 'UnderDogHero',
    avatar: '',
    winRate: 0.52,
    roi: 0.22,
    followers: 4900,
    streak: 2,
    tier: 'gold',
    isFollowing: true,
    recentPick: { matchId: 'match13', side: 'away', odds: 2.10 },
  },
  {
    id: 't11',
    username: 'LatinFury',
    avatar: '',
    winRate: 0.60,
    roi: 0.16,
    followers: 7800,
    streak: 6,
    tier: 'gold',
    isFollowing: false,
    recentPick: { matchId: 'match25', side: 'away', odds: 2.80 },
  },
  {
    id: 't12',
    username: 'EuroVision',
    avatar: '',
    winRate: 0.57,
    roi: 0.14,
    followers: 5400,
    streak: 3,
    tier: 'gold',
    isFollowing: false,
  },
  // ── Silver ─────────────────────────────────────────────────────────────────
  {
    id: 't13',
    username: 'BetRobot',
    avatar: '',
    winRate: 0.55,
    roi: 0.10,
    followers: 2800,
    streak: 4,
    tier: 'silver',
    isFollowing: false,
    recentPick: { matchId: 'match17', side: 'home', odds: 1.90 },
  },
  {
    id: 't14',
    username: 'ColdBlood',
    avatar: '',
    winRate: 0.53,
    roi: 0.09,
    followers: 2200,
    streak: 2,
    tier: 'silver',
    isFollowing: false,
  },
  {
    id: 't15',
    username: 'GolDeOuro',
    avatar: '',
    winRate: 0.56,
    roi: 0.11,
    followers: 3100,
    streak: 3,
    tier: 'silver',
    isFollowing: true,
  },
  {
    id: 't16',
    username: 'MegaTip',
    avatar: '',
    winRate: 0.51,
    roi: 0.06,
    followers: 1600,
    streak: 1,
    tier: 'silver',
    isFollowing: false,
    recentPick: { matchId: 'match20', side: 'home', odds: 2.15 },
  },
  {
    id: 't17',
    username: 'SafePlay',
    avatar: '',
    winRate: 0.54,
    roi: 0.07,
    followers: 2500,
    streak: 2,
    tier: 'silver',
    isFollowing: false,
  },
  {
    id: 't18',
    username: 'BetCrack',
    avatar: '',
    winRate: 0.50,
    roi: 0.05,
    followers: 1900,
    streak: 0,
    tier: 'silver',
    isFollowing: false,
    recentPick: { matchId: 'match11', side: 'home', odds: 2.05 },
  },
  {
    id: 't19',
    username: 'FutebolPuro',
    avatar: '',
    winRate: 0.57,
    roi: 0.13,
    followers: 3400,
    streak: 5,
    tier: 'silver',
    isFollowing: false,
  },
  {
    id: 't20',
    username: 'OddsFinder',
    avatar: '',
    winRate: 0.52,
    roi: 0.08,
    followers: 2100,
    streak: 1,
    tier: 'silver',
    isFollowing: false,
  },
  // ── Bronze ─────────────────────────────────────────────────────────────────
  {
    id: 't21',
    username: 'Novato77',
    avatar: '',
    winRate: 0.45,
    roi: 0.01,
    followers: 340,
    streak: 1,
    tier: 'bronze',
    isFollowing: false,
  },
  {
    id: 't22',
    username: 'ChuteLivre',
    avatar: '',
    winRate: 0.48,
    roi: 0.03,
    followers: 580,
    streak: 2,
    tier: 'bronze',
    isFollowing: false,
    recentPick: { matchId: 'match12', side: 'home', odds: 1.65 },
  },
  {
    id: 't23',
    username: 'GreenDream',
    avatar: '',
    winRate: 0.42,
    roi: -0.02,
    followers: 210,
    streak: 0,
    tier: 'bronze',
    isFollowing: false,
  },
  {
    id: 't24',
    username: 'LuckyPick',
    avatar: '',
    winRate: 0.47,
    roi: 0.02,
    followers: 450,
    streak: 1,
    tier: 'bronze',
    isFollowing: false,
  },
  {
    id: 't25',
    username: 'TorneioKing',
    avatar: '',
    winRate: 0.44,
    roi: -0.01,
    followers: 390,
    streak: 0,
    tier: 'bronze',
    isFollowing: false,
  },
  {
    id: 't26',
    username: 'PalpiteBR',
    avatar: '',
    winRate: 0.46,
    roi: 0.00,
    followers: 520,
    streak: 2,
    tier: 'bronze',
    isFollowing: false,
  },
  {
    id: 't27',
    username: 'ApostaCerta',
    avatar: '',
    winRate: 0.43,
    roi: -0.03,
    followers: 280,
    streak: 0,
    tier: 'bronze',
    isFollowing: false,
  },
  {
    id: 't28',
    username: 'RookieBet',
    avatar: '',
    winRate: 0.40,
    roi: -0.05,
    followers: 150,
    streak: 0,
    tier: 'bronze',
    isFollowing: false,
  },
  {
    id: 't29',
    username: 'ViradaMagica',
    avatar: '',
    winRate: 0.49,
    roi: 0.04,
    followers: 620,
    streak: 3,
    tier: 'bronze',
    isFollowing: false,
    recentPick: { matchId: 'match28', side: 'away', odds: 2.85 },
  },
  {
    id: 't30',
    username: 'MetaGol',
    avatar: '',
    winRate: 0.41,
    roi: -0.04,
    followers: 180,
    streak: 0,
    tier: 'bronze',
    isFollowing: false,
  },
  {
    id: 't31',
    username: 'JogaBonito',
    avatar: '',
    winRate: 0.50,
    roi: 0.05,
    followers: 710,
    streak: 2,
    tier: 'bronze',
    isFollowing: false,
  },
];

// ─── Feed Posts ───────────────────────────────────────────────────────────────

export const MOCK_FEED: FeedPost[] = [
  {
    id: 'p1',
    type: 'pick',
    user: { id: 't5', username: 'AcePredict', avatar: '', tier: 'elite' },
    content: 'Arsenal em casa contra o Liverpool, momento perfeito para apostar no fora. Liverpool está em sequência incrível de 8 vitórias seguidas. Confiança máxima nessa pick. 🔥',
    match: {
      id: 'match2',
      league: 'Premier League',
      homeTeam: 'Arsenal',
      awayTeam: 'Liverpool',
      status: 'pre',
      odds: { home: 2.10, draw: 3.40, away: 1.85 },
      bettors: 5830,
    },
    pick: { side: 'away', odds: 1.85 },
    likes: 847,
    comments: 92,
    copies: 314,
    isLiked: false,
    createdAt: '14min',
  },
  {
    id: 'p2',
    type: 'result',
    user: { id: 't2', username: 'StatMaster', avatar: '', tier: 'gold' },
    content: '✅ VERDE! Barcelona 2×1 Atlético Madrid. Pick certeira mais uma vez. Sequência de 4 acertos consecutivos. Quem copiou colheu os frutos! 💰',
    match: {
      id: 'match4',
      league: 'La Liga',
      homeTeam: 'Barcelona',
      awayTeam: 'Atlético Madrid',
      status: 'finished',
      odds: { home: 1.72, draw: 3.50, away: 4.20 },
      bettors: 4110,
    },
    pick: { side: 'home', odds: 1.72 },
    likes: 1203,
    comments: 148,
    copies: 521,
    isLiked: true,
    createdAt: '1h',
  },
  {
    id: 'p3',
    type: 'pick',
    user: { id: 't1', username: 'KingBet', avatar: '', tier: 'elite' },
    content: 'Real Madrid × Bayern é o duelo da semana. Bernabéu está cheio, Mbappé em forma absurda. Pick no mandante com confiança. Quem tiver dúvida, olha meu histórico.',
    match: {
      id: 'match3',
      league: 'UEFA Champions League',
      homeTeam: 'Real Madrid',
      awayTeam: 'Bayern Munich',
      status: 'pre',
      odds: { home: 1.95, draw: 3.60, away: 2.20 },
      bettors: 8920,
    },
    pick: { side: 'home', odds: 1.95 },
    likes: 2341,
    comments: 307,
    copies: 892,
    isLiked: false,
    createdAt: '2h',
  },
  {
    id: 'p4',
    type: 'analysis',
    user: { id: 't2', username: 'StatMaster', avatar: '', tier: 'gold' },
    content: 'Análise do dia: Brasileirão está em fase decisiva. Flamengo em casa tem 78% de aproveitamento nessa temporada. Corinthians sem 3 titulares. Os dados não mentem. 📊',
    likes: 534,
    comments: 67,
    copies: 0,
    isLiked: false,
    createdAt: '3h',
  },
  {
    id: 'p5',
    type: 'pick',
    user: { id: 't3', username: 'ValueHunt', avatar: '', tier: 'gold' },
    content: 'Flamengo em casa contra Corinthians, jogo ao vivo, já 1×0 no segundo tempo. Odds do Fla ainda em 1.45 com 67 min rodados. Valor absurdo, entro agora. ⚡',
    match: {
      id: 'match1',
      league: 'Brasileirão Série A',
      homeTeam: 'Flamengo',
      awayTeam: 'Corinthians',
      status: 'live',
      minute: 67,
      score: { home: 1, away: 0 },
      odds: { home: 1.45, draw: 3.80, away: 6.50 },
      bettors: 2470,
    },
    pick: { side: 'home', odds: 1.45 },
    likes: 389,
    comments: 44,
    copies: 167,
    isLiked: false,
    createdAt: '8min',
  },
  {
    id: 'p6',
    type: 'analysis',
    user: { id: 't5', username: 'AcePredict', avatar: '', tier: 'elite' },
    content: 'Minha semana: 11 picks, 8 verdes, 3 vermelhos. ROI da semana +31%. Não é sorte, é método. Quem está me seguindo desde o início está no lucro. Continuamos. 🎯',
    likes: 4102,
    comments: 512,
    copies: 0,
    isLiked: true,
    createdAt: '5h',
  },
  // ── New feed posts ─────────────────────────────────────────────────────────
  {
    id: 'p7',
    type: 'pick',
    user: { id: 't7', username: 'BrazilKing', avatar: '', tier: 'elite' },
    content: 'Palmeiras × São Paulo, clássico é sempre imprevisível mas Palmeiras em casa com elenco completo é outro nível. Mandante sem dúvidas.',
    match: {
      id: 'match7',
      league: 'Brasileirão Série A',
      homeTeam: 'Palmeiras',
      awayTeam: 'São Paulo',
      status: 'pre',
      odds: { home: 1.80, draw: 3.20, away: 4.50 },
      bettors: 4200,
    },
    pick: { side: 'home', odds: 1.80 },
    likes: 1120,
    comments: 134,
    copies: 445,
    isLiked: false,
    createdAt: '25min',
  },
  {
    id: 'p8',
    type: 'result',
    user: { id: 't8', username: 'ProSniper', avatar: '', tier: 'elite' },
    content: '✅ VERDE! Liverpool 3×1 Man City. Falei que o Liverpool ia atropelar e atropelou. 12ª sequência de greens. Recorde pessoal. Quem duvidou perdeu dinheiro. 🏆',
    match: {
      id: 'match38',
      league: 'Premier League',
      homeTeam: 'Liverpool',
      awayTeam: 'Manchester City',
      status: 'finished',
      score: { home: 3, away: 1 },
      odds: { home: 2.00, draw: 3.40, away: 3.50 },
      bettors: 8100,
    },
    pick: { side: 'home', odds: 2.00 },
    likes: 3890,
    comments: 421,
    copies: 1240,
    isLiked: true,
    createdAt: '45min',
  },
  {
    id: 'p9',
    type: 'pick',
    user: { id: 't9', username: 'DrawMaster', avatar: '', tier: 'gold' },
    content: 'Atlético Madrid × Real Madrid amanhã. Derby de Madrid no Metropolitano. Tudo aponta pra empate: últimos 4 confrontos, 3 empates. Vou no draw a 3.10. Especialidade da casa.',
    match: {
      id: 'match27',
      league: 'La Liga',
      homeTeam: 'Atlético Madrid',
      awayTeam: 'Real Madrid',
      status: 'pre',
      odds: { home: 2.80, draw: 3.10, away: 2.50 },
      bettors: 9300,
    },
    pick: { side: 'draw', odds: 3.10 },
    likes: 678,
    comments: 89,
    copies: 201,
    isLiked: false,
    createdAt: '1h',
  },
  {
    id: 'p10',
    type: 'analysis',
    user: { id: 't11', username: 'LatinFury', avatar: '', tier: 'gold' },
    content: 'Libertadores é outro campeonato. River × Flamengo hoje às 21:30. Altitude de Buenos Aires pesa, mas o Flamengo tem elenco pra aguentar. Olho nesse jogo. 🌎',
    likes: 890,
    comments: 102,
    copies: 0,
    isLiked: false,
    createdAt: '2h',
  },
  {
    id: 'p11',
    type: 'result',
    user: { id: 't1', username: 'KingBet', avatar: '', tier: 'elite' },
    content: '✅ VERDE! Inter 2×0 Milan. Derby della Madonnina dominado. Pick no mandante deu certo como sempre. Streak subindo. 💪',
    match: {
      id: 'match39',
      league: 'Serie A',
      homeTeam: 'Inter Milan',
      awayTeam: 'AC Milan',
      status: 'finished',
      score: { home: 2, away: 0 },
      odds: { home: 1.65, draw: 3.60, away: 5.00 },
      bettors: 4800,
    },
    pick: { side: 'home', odds: 1.65 },
    likes: 1567,
    comments: 178,
    copies: 623,
    isLiked: false,
    createdAt: '3h',
  },
  {
    id: 'p12',
    type: 'pick',
    user: { id: 't10', username: 'UnderDogHero', avatar: '', tier: 'gold' },
    content: 'Chelsea saindo na frente contra o United! Jogo ao vivo 0×1. Todo mundo subestimou o Chelsea fora de casa. Quem gosta de value, odds do Chelsea ainda pagando 2.10.',
    match: {
      id: 'match13',
      league: 'Premier League',
      homeTeam: 'Manchester United',
      awayTeam: 'Chelsea',
      status: 'live',
      minute: 22,
      score: { home: 0, away: 1 },
      odds: { home: 3.40, draw: 3.20, away: 2.10 },
      bettors: 4580,
    },
    pick: { side: 'away', odds: 2.10 },
    likes: 456,
    comments: 58,
    copies: 189,
    isLiked: false,
    createdAt: '5min',
  },
  {
    id: 'p13',
    type: 'challenge',
    user: { id: 't8', username: 'ProSniper', avatar: '', tier: 'elite' },
    content: 'DESAFIO: Quem acertar os 3 resultados da Champions de hoje ganha menção no meu perfil + badge especial. Barcelona, Real Madrid e City jogam hoje. Bora ver quem manja! 🏅',
    likes: 5200,
    comments: 892,
    copies: 0,
    isLiked: false,
    createdAt: '4h',
  },
  {
    id: 'p14',
    type: 'pick',
    user: { id: 't13', username: 'BetRobot', avatar: '', tier: 'silver' },
    content: 'Botafogo × Fluminense, clássico carioca. Botafogo mandante com campanha sólida em casa. Sem medo, pick na estrela solitária a 1.90.',
    match: {
      id: 'match17',
      league: 'Brasileirão Série A',
      homeTeam: 'Botafogo',
      awayTeam: 'Fluminense',
      status: 'pre',
      odds: { home: 1.90, draw: 3.30, away: 4.20 },
      bettors: 3680,
    },
    pick: { side: 'home', odds: 1.90 },
    likes: 234,
    comments: 31,
    copies: 78,
    isLiked: false,
    createdAt: '30min',
  },
  {
    id: 'p15',
    type: 'result',
    user: { id: 't3', username: 'ValueHunt', avatar: '', tier: 'gold' },
    content: '❌ RED. Palmeiras 0×0 Flamengo. Empate sem gols matou a pick no mandante. Faz parte, vamos pro próximo. Consistência é o que importa.',
    match: {
      id: 'match37',
      league: 'Brasileirão Série A',
      homeTeam: 'Palmeiras',
      awayTeam: 'Flamengo',
      status: 'finished',
      score: { home: 0, away: 0 },
      odds: { home: 1.85, draw: 3.30, away: 4.00 },
      bettors: 5200,
    },
    pick: { side: 'home', odds: 1.85 },
    likes: 312,
    comments: 56,
    copies: 0,
    isLiked: false,
    createdAt: '6h',
  },
  {
    id: 'p16',
    type: 'analysis',
    user: { id: 't7', username: 'BrazilKing', avatar: '', tier: 'elite' },
    content: 'Dados da rodada: Bundesliga mandante ganhou 7 de 9 jogos na última rodada. Bayern × Leverkusen ao vivo agora 1×1 quebrando o padrão. Atenção nos jogos de amanhã. 📈',
    likes: 760,
    comments: 85,
    copies: 0,
    isLiked: true,
    createdAt: '1h',
  },
  {
    id: 'p17',
    type: 'pick',
    user: { id: 't15', username: 'GolDeOuro', avatar: '', tier: 'silver' },
    content: 'Barcelona × Inter Milan na Champions hoje. Barça no Camp Nou é avassalador, 90% de aproveitamento em casa na UCL. Mandante sem pensar duas vezes.',
    match: {
      id: 'match21',
      league: 'UEFA Champions League',
      homeTeam: 'Barcelona',
      awayTeam: 'Inter Milan',
      status: 'pre',
      odds: { home: 1.60, draw: 3.90, away: 5.00 },
      bettors: 7400,
    },
    pick: { side: 'home', odds: 1.60 },
    likes: 345,
    comments: 42,
    copies: 123,
    isLiked: false,
    createdAt: '2h',
  },
  {
    id: 'p18',
    type: 'result',
    user: { id: 't5', username: 'AcePredict', avatar: '', tier: 'elite' },
    content: '✅ VERDE! Chelsea 0×1 Arsenal. Arsenal dominando fora de casa, exatamente como previ. Mais um acerto na Premier League. Método funciona.',
    match: {
      id: 'match45',
      league: 'Premier League',
      homeTeam: 'Chelsea',
      awayTeam: 'Arsenal',
      status: 'finished',
      score: { home: 0, away: 1 },
      odds: { home: 2.70, draw: 3.20, away: 2.60 },
      bettors: 5400,
    },
    pick: { side: 'away', odds: 2.60 },
    likes: 2100,
    comments: 267,
    copies: 780,
    isLiked: true,
    createdAt: '4h',
  },
  {
    id: 'p19',
    type: 'challenge',
    user: { id: 't7', username: 'BrazilKing', avatar: '', tier: 'elite' },
    content: 'DESAFIO BRASILEIRÃO: Acerte o placar exato de Palmeiras × São Paulo hoje. Quem chegar mais perto ganha 500 coins. Meu palpite: 2×1 Palmeiras. E o seu? ⚽',
    likes: 3400,
    comments: 1240,
    copies: 0,
    isLiked: false,
    createdAt: '3h',
  },
  {
    id: 'p20',
    type: 'pick',
    user: { id: 't11', username: 'LatinFury', avatar: '', tier: 'gold' },
    content: 'River Plate × Flamengo na Libertadores. Confio no Mengão visitante, time acostumado com pressão. Fla a 2.80 é presente.',
    match: {
      id: 'match25',
      league: 'Copa Libertadores',
      homeTeam: 'River Plate',
      awayTeam: 'Flamengo',
      status: 'pre',
      odds: { home: 2.30, draw: 3.10, away: 2.80 },
      bettors: 6200,
    },
    pick: { side: 'away', odds: 2.80 },
    likes: 920,
    comments: 134,
    copies: 310,
    isLiked: false,
    createdAt: '1h',
  },
  {
    id: 'p21',
    type: 'result',
    user: { id: 't9', username: 'DrawMaster', avatar: '', tier: 'gold' },
    content: '✅ VERDE! Liverpool 2×2 Barcelona na Champions. Empate a 3.40 cravado! Especialista em draws não falha. 5ª vez esse mês. 🎯',
    match: {
      id: 'match42',
      league: 'UEFA Champions League',
      homeTeam: 'Liverpool',
      awayTeam: 'Barcelona',
      status: 'finished',
      score: { home: 2, away: 2 },
      odds: { home: 2.20, draw: 3.40, away: 3.10 },
      bettors: 9800,
    },
    pick: { side: 'draw', odds: 3.40 },
    likes: 1890,
    comments: 234,
    copies: 567,
    isLiked: false,
    createdAt: '5h',
  },
  {
    id: 'p22',
    type: 'analysis',
    user: { id: 't12', username: 'EuroVision', avatar: '', tier: 'gold' },
    content: 'Premier League: 6 das últimas 8 rodadas tiveram mais de 2.5 gols por jogo em média. Tottenham × Newcastle amanhã promete ser jogo aberto. Under/over é o caminho. 📊',
    likes: 420,
    comments: 53,
    copies: 0,
    isLiked: false,
    createdAt: '4h',
  },
  {
    id: 'p23',
    type: 'pick',
    user: { id: 't19', username: 'FutebolPuro', avatar: '', tier: 'silver' },
    content: 'Man City × PSG amanhã na Champions. City em casa é praticamente imbatível na UCL. Haaland vs Mbappé mas o coletivo do City é superior.',
    match: {
      id: 'match9',
      league: 'UEFA Champions League',
      homeTeam: 'Manchester City',
      awayTeam: 'PSG',
      status: 'pre',
      odds: { home: 1.70, draw: 3.80, away: 4.80 },
      bettors: 11200,
    },
    pick: { side: 'home', odds: 1.70 },
    likes: 278,
    comments: 34,
    copies: 89,
    isLiked: false,
    createdAt: '2h',
  },
  {
    id: 'p24',
    type: 'result',
    user: { id: 't7', username: 'BrazilKing', avatar: '', tier: 'elite' },
    content: '✅ VERDE! Flamengo 3×1 Boca Juniors na Libertadores. Mengão destruiu na Maracanã. Quem seguiu minha pick em 1.80 tá comemorando! 🇧🇷',
    match: {
      id: 'match44',
      league: 'Copa Libertadores',
      homeTeam: 'Flamengo',
      awayTeam: 'Boca Juniors',
      status: 'finished',
      score: { home: 3, away: 1 },
      odds: { home: 1.80, draw: 3.40, away: 4.20 },
      bettors: 7600,
    },
    pick: { side: 'home', odds: 1.80 },
    likes: 2780,
    comments: 345,
    copies: 890,
    isLiked: true,
    createdAt: '7h',
  },
  {
    id: 'p25',
    type: 'analysis',
    user: { id: 't1', username: 'KingBet', avatar: '', tier: 'elite' },
    content: 'Semana de Champions League sempre movimenta o mercado. Observem as odds de City × PSG: casa forte demais, PSG supervalorizado. Aguardem minha pick oficial amanhã cedo.',
    likes: 1340,
    comments: 178,
    copies: 0,
    isLiked: false,
    createdAt: '6h',
  },
  {
    id: 'p26',
    type: 'pick',
    user: { id: 't22', username: 'ChuteLivre', avatar: '', tier: 'bronze' },
    content: 'Atlético Mineiro × Grêmio amanhã. Galo em casa é pedra, mandante a 1.65 tá praticamente dado. Minha primeira pick do dia!',
    match: {
      id: 'match12',
      league: 'Brasileirão Série A',
      homeTeam: 'Atlético Mineiro',
      awayTeam: 'Grêmio',
      status: 'pre',
      odds: { home: 1.65, draw: 3.50, away: 5.20 },
      bettors: 2140,
    },
    pick: { side: 'home', odds: 1.65 },
    likes: 87,
    comments: 12,
    copies: 23,
    isLiked: false,
    createdAt: '20min',
  },
  {
    id: 'p27',
    type: 'result',
    user: { id: 't10', username: 'UnderDogHero', avatar: '', tier: 'gold' },
    content: '❌ RED. Bayern 3×1 Dortmund. Apostei no underdog mas Bayern foi implacável fora de casa. Às vezes o gigante vence mesmo. Próxima!',
    match: {
      id: 'match40',
      league: 'Bundesliga',
      homeTeam: 'Borussia Dortmund',
      awayTeam: 'Bayern Munich',
      status: 'finished',
      score: { home: 1, away: 3 },
      odds: { home: 3.10, draw: 3.40, away: 2.15 },
      bettors: 6300,
    },
    pick: { side: 'home', odds: 3.10 },
    likes: 198,
    comments: 45,
    copies: 0,
    isLiked: false,
    createdAt: '8h',
  },
  {
    id: 'p28',
    type: 'challenge',
    user: { id: 't5', username: 'AcePredict', avatar: '', tier: 'elite' },
    content: 'DESAFIO SEMANAL: Quem conseguir 5 greens consecutivos essa semana ganha acesso ao meu grupo VIP por 1 mês. Postem seus resultados aqui! 🔥',
    likes: 6700,
    comments: 1580,
    copies: 0,
    isLiked: true,
    createdAt: '12h',
  },
  {
    id: 'p29',
    type: 'pick',
    user: { id: 't16', username: 'MegaTip', avatar: '', tier: 'silver' },
    content: 'Milan × Atalanta hoje. Milan em San Siro precisa dos 3 pontos. Atalanta é forte mas o fator casa pesa. Vou de mandante.',
    match: {
      id: 'match20',
      league: 'Serie A',
      homeTeam: 'AC Milan',
      awayTeam: 'Atalanta',
      status: 'pre',
      odds: { home: 2.15, draw: 3.25, away: 3.40 },
      bettors: 2450,
    },
    pick: { side: 'home', odds: 2.15 },
    likes: 156,
    comments: 22,
    copies: 45,
    isLiked: false,
    createdAt: '40min',
  },
  {
    id: 'p30',
    type: 'analysis',
    user: { id: 't15', username: 'GolDeOuro', avatar: '', tier: 'silver' },
    content: 'Levantamento da semana: times brasileiros na Libertadores têm 65% de aproveitamento como visitantes nesta edição. Dado forte pra quem tá olhando River × Fla. 📋',
    likes: 310,
    comments: 40,
    copies: 0,
    isLiked: false,
    createdAt: '3h',
  },
  {
    id: 'p31',
    type: 'pick',
    user: { id: 't29', username: 'ViradaMagica', avatar: '', tier: 'bronze' },
    content: 'Vasco × Fortaleza amanhã. Fortaleza tá voando no Brasileirão, melhor visitante. Arrisco no visitante a 2.85. Quem sabe não vem o green!',
    match: {
      id: 'match28',
      league: 'Brasileirão Série A',
      homeTeam: 'Vasco',
      awayTeam: 'Fortaleza',
      status: 'pre',
      odds: { home: 2.60, draw: 3.00, away: 2.85 },
      bettors: 1780,
    },
    pick: { side: 'away', odds: 2.85 },
    likes: 64,
    comments: 8,
    copies: 12,
    isLiked: false,
    createdAt: '15min',
  },
  {
    id: 'p32',
    type: 'result',
    user: { id: 't11', username: 'LatinFury', avatar: '', tier: 'gold' },
    content: '✅ VERDE! São Paulo 1×2 Botafogo. Apostei no visitante e Botafogo não decepcionou. Fogão é o time da vez no Brasil!',
    match: {
      id: 'match43',
      league: 'Brasileirão Série A',
      homeTeam: 'São Paulo',
      awayTeam: 'Botafogo',
      status: 'finished',
      score: { home: 1, away: 2 },
      odds: { home: 2.10, draw: 3.20, away: 3.50 },
      bettors: 2800,
    },
    pick: { side: 'away', odds: 3.50 },
    likes: 980,
    comments: 112,
    copies: 340,
    isLiked: false,
    createdAt: '9h',
  },
  {
    id: 'p33',
    type: 'analysis',
    user: { id: 't8', username: 'ProSniper', avatar: '', tier: 'elite' },
    content: 'Relatório mensal: 47 picks, 35 verdes, 12 vermelhos. Win rate de 74.5% e ROI de +35%. Melhor mês da minha carreira. Disciplina e análise vencem no longo prazo. 📊🏆',
    likes: 8900,
    comments: 1100,
    copies: 0,
    isLiked: true,
    createdAt: '10h',
  },
  {
    id: 'p34',
    type: 'challenge',
    user: { id: 't1', username: 'KingBet', avatar: '', tier: 'elite' },
    content: 'DESAFIO: Aposte em pelo menos 1 jogo de cada liga hoje (Premier, La Liga, Serie A, Bundesliga, Brasileirão). Quem acertar todas ganha reconhecimento! 👑',
    likes: 4500,
    comments: 780,
    copies: 0,
    isLiked: false,
    createdAt: '6h',
  },
  {
    id: 'p35',
    type: 'result',
    user: { id: 't13', username: 'BetRobot', avatar: '', tier: 'silver' },
    content: '✅ VERDE! Grêmio 2×1 Internacional. Grenal disputado mas Grêmio levou em casa. Streak de 4 acertos!',
    match: {
      id: 'match50',
      league: 'Brasileirão Série A',
      homeTeam: 'Grêmio',
      awayTeam: 'Internacional',
      status: 'finished',
      score: { home: 2, away: 1 },
      odds: { home: 2.30, draw: 3.00, away: 3.20 },
      bettors: 4600,
    },
    pick: { side: 'home', odds: 2.30 },
    likes: 340,
    comments: 48,
    copies: 95,
    isLiked: false,
    createdAt: '11h',
  },
  {
    id: 'p36',
    type: 'pick',
    user: { id: 't12', username: 'EuroVision', avatar: '', tier: 'gold' },
    content: 'Boca × Palmeiras amanhã na Libertadores. La Bombonera é inferno, Boca em casa na Libertadores é outra coisa. Mandante a 2.40.',
    match: {
      id: 'match33',
      league: 'Copa Libertadores',
      homeTeam: 'Boca Juniors',
      awayTeam: 'Palmeiras',
      status: 'pre',
      odds: { home: 2.40, draw: 3.00, away: 2.90 },
      bettors: 5800,
    },
    pick: { side: 'home', odds: 2.40 },
    likes: 567,
    comments: 78,
    copies: 156,
    isLiked: false,
    createdAt: '2h',
  },
  {
    id: 'p37',
    type: 'analysis',
    user: { id: 't14', username: 'ColdBlood', avatar: '', tier: 'silver' },
    content: 'Análise fria: International × Cruzeiro ao vivo, 2×2 com 55 min. Jogo aberto, odds de empate caindo. Quem entrou no draw tá bem posicionado. Sem emoção, só números.',
    likes: 189,
    comments: 25,
    copies: 0,
    isLiked: false,
    createdAt: '10min',
  },
  {
    id: 'p38',
    type: 'pick',
    user: { id: 't18', username: 'BetCrack', avatar: '', tier: 'silver' },
    content: 'Dortmund × Leipzig amanhã. BVB precisa reagir depois da derrota pro Bayern. Signal Wall tá forte no mandante. Vou de Dortmund.',
    match: {
      id: 'match11',
      league: 'Bundesliga',
      homeTeam: 'Borussia Dortmund',
      awayTeam: 'RB Leipzig',
      status: 'pre',
      odds: { home: 2.05, draw: 3.40, away: 3.50 },
      bettors: 3870,
    },
    pick: { side: 'home', odds: 2.05 },
    likes: 120,
    comments: 18,
    copies: 34,
    isLiked: false,
    createdAt: '50min',
  },
  {
    id: 'p39',
    type: 'result',
    user: { id: 't2', username: 'StatMaster', avatar: '', tier: 'gold' },
    content: '✅ VERDE! Real Madrid 4×0 Sevilla. Goleada histórica, pick fácil no mandante. Dados apontavam, resultado confirmou. 4 greens na sequência! 📊💰',
    match: {
      id: 'match41',
      league: 'La Liga',
      homeTeam: 'Real Madrid',
      awayTeam: 'Sevilla',
      status: 'finished',
      score: { home: 4, away: 0 },
      odds: { home: 1.35, draw: 4.80, away: 8.00 },
      bettors: 3900,
    },
    pick: { side: 'home', odds: 1.35 },
    likes: 1450,
    comments: 190,
    copies: 410,
    isLiked: true,
    createdAt: '8h',
  },
  {
    id: 'p40',
    type: 'challenge',
    user: { id: 't11', username: 'LatinFury', avatar: '', tier: 'gold' },
    content: 'DESAFIO LIBERTADORES: River × Fla e Boca × Palmeiras essa semana. Acerte os dois resultados e me marca. Vou repostar os melhores palpites! 🏆🌎',
    likes: 2300,
    comments: 670,
    copies: 0,
    isLiked: false,
    createdAt: '5h',
  },
  {
    id: 'p41',
    type: 'analysis',
    user: { id: 't10', username: 'UnderDogHero', avatar: '', tier: 'gold' },
    content: 'Underdogs da semana: Brighton a 1.60 contra Everton amanhã é suspeito. Everton tem surpreendido fora. Fiquem de olho em odds acima de 4.00 nesse jogo.',
    likes: 380,
    comments: 47,
    copies: 0,
    isLiked: false,
    createdAt: '3h',
  },
  {
    id: 'p42',
    type: 'result',
    user: { id: 't19', username: 'FutebolPuro', avatar: '', tier: 'silver' },
    content: '❌ RED. Roma 0×1 Juventus. Apostei na Roma em casa mas a Juve segurou. Duas derrotas seguidas, hora de recalibrar a estratégia.',
    match: {
      id: 'match49',
      league: 'Serie A',
      homeTeam: 'Roma',
      awayTeam: 'Juventus',
      status: 'finished',
      score: { home: 0, away: 1 },
      odds: { home: 2.90, draw: 3.10, away: 2.50 },
      bettors: 3500,
    },
    pick: { side: 'home', odds: 2.90 },
    likes: 145,
    comments: 28,
    copies: 0,
    isLiked: false,
    createdAt: '7h',
  },
  {
    id: 'p43',
    type: 'pick',
    user: { id: 't4', username: 'GoalGuru', avatar: '', tier: 'silver' },
    content: 'Sevilla × Betis ao vivo, derby andaluz! Sevilla ganhando 1×0 com 72 min. Mandante seguro, odds caindo. Pode ser tarde mas ainda tem valor.',
    match: {
      id: 'match15',
      league: 'La Liga',
      homeTeam: 'Sevilla',
      awayTeam: 'Real Betis',
      status: 'live',
      minute: 72,
      score: { home: 1, away: 0 },
      odds: { home: 1.55, draw: 4.00, away: 5.80 },
      bettors: 1340,
    },
    pick: { side: 'home', odds: 1.55 },
    likes: 210,
    comments: 29,
    copies: 67,
    isLiked: false,
    createdAt: '3min',
  },
  {
    id: 'p44',
    type: 'result',
    user: { id: 't8', username: 'ProSniper', avatar: '', tier: 'elite' },
    content: '✅ VERDE! PSG 2×0 Marseille na Ligue 1. Pick tranquila no PSG em casa. Dominação total. Continuamos no topo do ranking.',
    match: {
      id: 'match46',
      league: 'Ligue 1',
      homeTeam: 'PSG',
      awayTeam: 'Marseille',
      status: 'finished',
      score: { home: 2, away: 0 },
      odds: { home: 1.40, draw: 4.50, away: 7.00 },
      bettors: 3200,
    },
    pick: { side: 'home', odds: 1.40 },
    likes: 1670,
    comments: 198,
    copies: 520,
    isLiked: false,
    createdAt: '9h',
  },
  // ── Extra posts: Libertadores, Copa do Brasil, challenges ──────────────
  { id: 'p48', type: 'pick', user: { id: 't8', username: 'ProSniper', avatar: '', tier: 'elite' }, content: 'Superclássico Boca × River ao vivo! Empate no placar, mas o River tá pressionando. Pick no River nos últimos 20min. 🔥', match: { id: 'match51', league: 'Libertadores', homeTeam: 'Boca Juniors', awayTeam: 'River Plate', status: 'live', minute: 72, score: { home: 1, away: 1 }, odds: { home: 2.40, draw: 3.10, away: 2.80 }, bettors: 14200 }, pick: { side: 'away', odds: 2.80 }, likes: 3210, comments: 412, copies: 890, isLiked: false, createdAt: '2min' },
  { id: 'p49', type: 'result', user: { id: 't5', username: 'AcePredict', avatar: '', tier: 'elite' }, content: '✅ VERDE! Palmeiras 3×1 Boca na Libertadores. Quem seguiu minha pick colheu os frutos! Sequência de 11 acertos! 💰💰', match: { id: 'match54', league: 'Libertadores', homeTeam: 'Palmeiras', awayTeam: 'Boca Juniors', status: 'finished', score: { home: 3, away: 1 }, odds: { home: 1.65, draw: 3.50, away: 5.00 }, bettors: 9800 }, pick: { side: 'home', odds: 1.65 }, likes: 5420, comments: 678, copies: 1340, isLiked: true, createdAt: '30min' },
  { id: 'p50', type: 'challenge', user: { id: 't1', username: 'KingBet', avatar: '', tier: 'elite' }, content: '🏆 DESAFIO: Quem acerta mais resultados da Champions? Eu aposto que Real Madrid, Man City e Bayern avançam. Quem discorda? Comenta aí! ⚔️', likes: 4100, comments: 892, copies: 0, isLiked: false, createdAt: '1h' },
  { id: 'p51', type: 'analysis', user: { id: 't2', username: 'StatMaster', avatar: '', tier: 'gold' }, content: 'Copa do Brasil: Flamengo em casa é imbatível. 2×0 no primeiro tempo contra Cruzeiro. Aproveitamento de 92% como mandante na Copa. Números não mentem. 📊', likes: 1890, comments: 234, copies: 0, isLiked: false, createdAt: '45min' },
  { id: 'p52', type: 'pick', user: { id: 't10', username: 'DrawMaster', avatar: '', tier: 'gold' }, content: 'Man United × Chelsea é clássico de empate. Últimos 4 confrontos: 3 empates. Odd de 3.20 no empate tem valor absurdo. Confia no mestre dos empates! 🤝', match: { id: 'match56', league: 'Premier League', homeTeam: 'Manchester United', awayTeam: 'Chelsea', status: 'pre', odds: { home: 2.50, draw: 3.20, away: 2.80 }, bettors: 8900 }, pick: { side: 'draw', odds: 3.20 }, likes: 1670, comments: 289, copies: 456, isLiked: false, createdAt: '1h' },
  { id: 'p53', type: 'challenge', user: { id: 't3', username: 'ValueHunt', avatar: '', tier: 'gold' }, content: '⚡ DESAFIO DA SEMANA: 5 picks em 5 dias, todas com odds acima de 2.00. Aceita? Quem completar ganha badge exclusivo! Primeiro pick: Ajax × PSV, pick no Ajax. 🎯', likes: 2340, comments: 567, copies: 0, isLiked: false, createdAt: '2h' },
  { id: 'p54', type: 'pick', user: { id: 't12', username: 'LatinFury', avatar: '', tier: 'gold' }, content: 'Benfica × Porto, O Clássico! Benfica em casa com 85% de aproveitamento. Odds 2.10 caindo rápido. Entra agora antes que desça mais! 🇵🇹', match: { id: 'match68', league: 'Liga Portugal', homeTeam: 'Benfica', awayTeam: 'Porto', status: 'pre', odds: { home: 2.10, draw: 3.20, away: 3.40 }, bettors: 5100 }, pick: { side: 'home', odds: 2.10 }, likes: 980, comments: 145, copies: 312, isLiked: false, createdAt: '3h' },
  { id: 'p55', type: 'analysis', user: { id: 't5', username: 'AcePredict', avatar: '', tier: 'elite' }, content: 'Análise semanal: 14 picks, 11 verdes, 3 vermelhos. ROI da semana +31%. Melhor semana de 2026. O método funciona. Quem segue, lucra. 🚀', likes: 6780, comments: 890, copies: 0, isLiked: true, createdAt: '4h' },
  { id: 'p56', type: 'pick', user: { id: 't14', username: 'BetCrack', avatar: '', tier: 'silver' }, content: 'Bayern × Leverkusen amanhã. Bayern favorito mas Leverkusen é perigoso fora. Pick no Bayern com cautela. Odds 1.75 justo. ⚽', match: { id: 'match63', league: 'Bundesliga', homeTeam: 'Bayern Munich', awayTeam: 'Bayer Leverkusen', status: 'pre', odds: { home: 1.75, draw: 3.80, away: 4.20 }, bettors: 7800 }, pick: { side: 'home', odds: 1.75 }, likes: 450, comments: 67, copies: 123, isLiked: false, createdAt: '5h' },
  { id: 'p57', type: 'result', user: { id: 't3', username: 'ValueHunt', avatar: '', tier: 'gold' }, content: '❌ VERMELHO. Atlético MG 0×2 River Plate. Perdi essa. Mas o método segue: 19 verdes em 25 picks. Reset mental e bora pro próximo! 💪', match: { id: 'match55', league: 'Libertadores', homeTeam: 'River Plate', awayTeam: 'Atlético Mineiro', status: 'finished', score: { home: 0, away: 2 }, odds: { home: 2.20, draw: 3.30, away: 3.10 }, bettors: 7400 }, pick: { side: 'home', odds: 2.20 }, likes: 890, comments: 156, copies: 0, isLiked: false, createdAt: '6h' },
  { id: 'p58', type: 'challenge', user: { id: 't8', username: 'ProSniper', avatar: '', tier: 'elite' }, content: '🎯 TORNEIO ATIVO: Quem está no Torneio Champions League? Estou em #42 com 850 pontos. Meta: top 10 até amanhã. Quem me alcança? 🏆', likes: 3450, comments: 567, copies: 0, isLiked: false, createdAt: '7h' },
];

// ─── Missions ─────────────────────────────────────────────────────────────────

export const MOCK_MISSIONS: Mission[] = [
  {
    id: 'm1',
    title: 'Primeira aposta do dia',
    description: 'Faça pelo menos 1 aposta hoje',
    xpReward: 100,
    coinsReward: 50,
    progress: 1,
    target: 1,
    type: 'daily',
    completed: true,
    revealed: true,
  },
  {
    id: 'm2',
    title: 'Copiar 1 tipster',
    description: 'Use o copy bet em qualquer post',
    xpReward: 150,
    coinsReward: 75,
    progress: 0,
    target: 1,
    type: 'daily',
    completed: false,
    revealed: true,
  },
  {
    id: 'm3',
    title: 'Seguir 3 tipsters',
    description: 'Expanda sua rede de análises',
    xpReward: 200,
    coinsReward: 100,
    progress: 2,
    target: 3,
    type: 'daily',
    completed: false,
    revealed: true,
  },
  {
    id: 'm4',
    title: '???',
    description: 'Faça apostas nesta tela para revelar',
    xpReward: 500,
    coinsReward: 250,
    progress: 0,
    target: 3,
    type: 'hidden',
    completed: false,
    revealed: false,
    hiddenTitle: 'Apostador Ativo',
    hiddenDescription: 'Faça 3 apostas em um único dia — missão dominada!',
  },
  // ── New missions ───────────────────────────────────────────────────────────
  {
    id: 'm5',
    title: 'Check-in diário',
    description: 'Abra o app e faça login',
    xpReward: 50,
    coinsReward: 25,
    progress: 1,
    target: 1,
    type: 'daily',
    completed: true,
    revealed: true,
  },
  {
    id: 'm6',
    title: 'Acumular 5 greens na semana',
    description: 'Tenha 5 apostas vencedoras em 7 dias',
    xpReward: 400,
    coinsReward: 200,
    progress: 3,
    target: 5,
    type: 'weekly',
    completed: false,
    revealed: true,
  },
  {
    id: 'm7',
    title: 'Apostar em 3 ligas diferentes',
    description: 'Diversifique suas apostas entre ligas',
    xpReward: 300,
    coinsReward: 150,
    progress: 1,
    target: 3,
    type: 'weekly',
    completed: false,
    revealed: true,
  },
  {
    id: 'm8',
    title: 'Curtir 10 posts no feed',
    description: 'Interaja com a comunidade',
    xpReward: 250,
    coinsReward: 120,
    progress: 6,
    target: 10,
    type: 'weekly',
    completed: false,
    revealed: true,
  },
  {
    id: 'm9',
    title: 'Ganhar 500 XP na semana',
    description: 'Acumule experiência com suas atividades',
    xpReward: 500,
    coinsReward: 250,
    progress: 320,
    target: 500,
    type: 'weekly',
    completed: false,
    revealed: true,
  },
  {
    id: 'm10',
    title: '???',
    description: 'Continue apostando para revelar',
    xpReward: 750,
    coinsReward: 400,
    progress: 0,
    target: 5,
    type: 'hidden',
    completed: false,
    revealed: false,
    hiddenTitle: 'Streak Master',
    hiddenDescription: 'Alcance uma sequência de 5 greens consecutivos',
  },
  {
    id: 'm11',
    title: '???',
    description: 'Explore o app para descobrir',
    xpReward: 1000,
    coinsReward: 500,
    progress: 0,
    target: 1,
    type: 'hidden',
    completed: false,
    revealed: false,
    hiddenTitle: 'Influenciador',
    hiddenDescription: 'Tenha 10 cópias em uma única pick',
  },
  {
    id: 'm12',
    title: '???',
    description: 'Jogue mais para desbloquear',
    xpReward: 600,
    coinsReward: 300,
    progress: 0,
    target: 10,
    type: 'hidden',
    completed: false,
    revealed: false,
    hiddenTitle: 'Maratonista',
    hiddenDescription: 'Aposte em 10 jogos diferentes em um único dia',
  },
];

// ─── Leaderboard Users ───────────────────────────────────────────────────────

const mkUser = (
  id: string,
  username: string,
  level: number,
  xp: number,
  xpToNext: number,
  streak: number,
  rank: number,
  winRate: number,
  roi: number,
  clan: string | null = null,
  following: string[] = [],
): User => ({
  id,
  username,
  avatar: '',
  level,
  xp,
  xpToNext,
  streak,
  balance: 0,
  coins: 0,
  rank,
  winRate,
  roi,
  clan,
  badges: [],
  following,
  dna: { style: '', strengths: [], riskProfile: 'moderate' },
  state: 'motivated',
  hasCompletedOnboarding: true,
});

export const MOCK_LEADERBOARD: User[] = [
  mkUser('lb1', 'AcePredict',     14, 2800, 3500, 11, 1,  0.72, 0.31, 'c1'),
  mkUser('lb2', 'KingBet',        12, 2100, 3000, 7,  2,  0.68, 0.24, 'c1'),
  mkUser('lb3', 'SharkBets',      11, 1950, 2800, 9,  3,  0.65, 0.22, 'c2'),
  mkUser('lb4', 'LuckyStrike',    10, 1700, 2500, 6,  4,  0.63, 0.20, 'c2'),
  mkUser('lb5', 'StatMaster',     10, 1680, 2500, 4,  5,  0.61, 0.15, 'c3'),
  mkUser('lb6', 'BetNinja',        9, 1400, 2200, 5,  6,  0.60, 0.18, 'c1'),
  mkUser('lb7', 'ValueHunt',       8, 1200, 2000, 3,  7,  0.58, 0.19, 'c3'),
  mkUser('lb8', 'ProPunter',       7, 980,  1800, 4,  8,  0.57, 0.14, null),
  mkUser('lb9', 'OddsWhiz',        7, 920,  1800, 2,  9,  0.55, 0.11, 'c4'),
  mkUser('lb10','GoalMachine',     6, 850,  1600, 3,  10, 0.54, 0.10, 'c2'),
  mkUser('lb11','ClutchKing',      6, 780,  1600, 2,  11, 0.53, 0.09, null),
  mkUser('lb12','BetBoss',         5, 620,  1400, 1,  12, 0.52, 0.08, 'c4'),
  mkUser('lb13','TipMaster99',     5, 580,  1400, 3,  13, 0.51, 0.07, 'c5'),
  mkUser('lb14','RiskTaker',       4, 450,  1200, 2,  14, 0.50, 0.06, null),
  mkUser('lb15','SmartMoney',      4, 400,  1200, 1,  15, 0.49, 0.05, 'c3'),
  mkUser('lb16','OddsBreaker',     3, 320,  1000, 1,  16, 0.48, 0.04, 'c5'),
  mkUser('lb17','BetWarrior',      3, 280,  1000, 0,  17, 0.47, 0.03, null),
  mkUser('lb18','GreenHunter',     2, 220,  800,  1,  18, 0.46, 0.02, 'c6'),
  mkUser('lb19','LiveBetter',      2, 180,  800,  0,  19, 0.45, 0.01, null),
  mkUser('lb20','Rookie10',        1, 120,  500,  0,  20, 0.40, 0.00, 'c6'),
];

// ─── Clans ───────────────────────────────────────────────────────────────────

export const MOCK_CLANS: Clan[] = [
  { id: 'c1', name: 'Sharks Elite',    tag: 'SHK', members: 48, rank: 1, xp: 84200, weeklyXp: 12400, badge: '🦈' },
  { id: 'c2', name: 'Golden Bets',     tag: 'GLD', members: 42, rank: 2, xp: 79800, weeklyXp: 11800, badge: '🏆' },
  { id: 'c3', name: 'Value Hunters',   tag: 'VLH', members: 35, rank: 3, xp: 67500, weeklyXp: 9200,  badge: '🎯' },
  { id: 'c4', name: 'Odds Crushers',   tag: 'ODS', members: 31, rank: 4, xp: 58100, weeklyXp: 7600,  badge: '💎' },
  { id: 'c5', name: 'Tip Lords',       tag: 'TIP', members: 27, rank: 5, xp: 45300, weeklyXp: 6100,  badge: '👑' },
  { id: 'c6', name: 'Lucky Strike FC', tag: 'LSF', members: 22, rank: 6, xp: 31200, weeklyXp: 4300,  badge: '⚡' },
];

// ─── Power-Ups ──────────────────────────────────────────────────────────────

export const MOCK_POWER_UPS: PowerUp[] = [
  { id: 'pu1', type: 'xp_boost', name: 'XP Boost', description: 'Ganhe 2x XP por 1 hora', icon: '⚡', cost: 150, duration: 3600, active: false, expiresAt: null },
  { id: 'pu2', type: 'odds_shield', name: 'Odds Shield', description: 'Proteja suas odds por 30 min', icon: '🛡️', cost: 200, duration: 1800, active: false, expiresAt: null },
  { id: 'pu3', type: 'lucky_streak', name: 'Lucky Streak', description: 'Bônus de streak por 2 horas', icon: '🍀', cost: 300, duration: 7200, active: false, expiresAt: null },
];

// ─── Collective Predictions ─────────────────────────────────────────────────

export const MOCK_PREDICTIONS: CollectivePrediction[] = [
  { matchId: 'match1', home: 62, draw: 18, away: 20 },
  { matchId: 'match2', home: 38, draw: 22, away: 40 },
  { matchId: 'match3', home: 52, draw: 20, away: 28 },
  { matchId: 'match5', home: 44, draw: 30, away: 26 },
  { matchId: 'match6', home: 58, draw: 15, away: 27 },
  { matchId: 'match7', home: 55, draw: 25, away: 20 },
];

// ─── Notifications ──────────────────────────────────────────────────────────

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  { id: 'n1', type: 'bet_result', title: 'Aposta GREEN!', message: 'Barcelona 2x1 Atletico - Você ganhou R$ 34,40', icon: '✅', read: false, createdAt: '12 abr 22:30' },
  { id: 'n2', type: 'social', title: 'Novo seguidor', message: 'BetKing22 começou a te seguir', icon: '👤', read: false, createdAt: '12 abr 20:15' },
  { id: 'n3', type: 'mission', title: 'Missão completa!', message: 'Primeira aposta do dia - +100 XP', icon: '🎯', read: true, createdAt: '13 abr 10:00' },
  { id: 'n4', type: 'streak', title: 'Streak em risco!', message: 'Faça check-in hoje para manter sua sequência de 2 dias', icon: '🔥', read: false, createdAt: '13 abr 08:00' },
  { id: 'n5', type: 'season', title: 'Temporada Alpha', message: 'Faltam 3 dias para o fim da temporada. Suba no ranking!', icon: '🏆', read: false, createdAt: '13 abr 07:00' },
  { id: 'n6', type: 'system', title: 'Bem-vindo ao NEXA!', message: 'Complete o onboarding e ganhe 200 coins', icon: '🎉', read: true, createdAt: '10 abr 12:00' },
  // ── New notifications ──────────────────────────────────────────────────────
  { id: 'n7', type: 'bet_result', title: 'Aposta RED', message: 'Palmeiras 0x0 Flamengo - Aposta perdida R$ 20,00', icon: '❌', read: false, createdAt: '12 abr 23:45' },
  { id: 'n8', type: 'social', title: 'Pick copiada!', message: 'StatMaster copiou sua pick em Arsenal × Liverpool', icon: '📋', read: false, createdAt: '13 abr 09:30' },
  { id: 'n9', type: 'bet_result', title: 'Aposta GREEN!', message: 'Liverpool 3x1 Man City - Você ganhou R$ 52,00', icon: '✅', read: true, createdAt: '12 abr 19:00' },
  { id: 'n10', type: 'mission', title: 'Nova missão!', message: 'Missão semanal disponível: Acumular 5 greens', icon: '🎯', read: false, createdAt: '13 abr 00:00' },
  { id: 'n11', type: 'social', title: 'Menção em post', message: 'BrazilKing te mencionou em um desafio', icon: '💬', read: false, createdAt: '13 abr 11:00' },
  { id: 'n12', type: 'streak', title: 'Streak de 3 dias!', message: 'Parabéns! Você manteve sua sequência por 3 dias seguidos', icon: '🔥', read: true, createdAt: '12 abr 10:00' },
  { id: 'n13', type: 'system', title: 'Manutenção programada', message: 'O app estará em manutenção amanhã das 04:00 às 05:00', icon: '🔧', read: false, createdAt: '13 abr 12:00' },
  { id: 'n14', type: 'season', title: 'Recompensa disponível!', message: 'Você atingiu o rank Silver na temporada. Resgate seus coins!', icon: '🏅', read: false, createdAt: '13 abr 06:00' },
  { id: 'n15', type: 'bet_result', title: 'Aposta GREEN!', message: 'Inter 2x0 Milan - Você ganhou R$ 18,50', icon: '✅', read: true, createdAt: '11 abr 22:00' },
  { id: 'n16', type: 'social', title: '5 novos seguidores', message: 'Você ganhou 5 seguidores hoje. Continue compartilhando!', icon: '👥', read: true, createdAt: '12 abr 18:00' },
  { id: 'n17', type: 'mission', title: 'Missão quase completa!', message: 'Falta 1 curtida para completar "Curtir 10 posts"', icon: '⏳', read: false, createdAt: '13 abr 13:00' },
  { id: 'n18', type: 'streak', title: 'Bônus de streak!', message: 'Streak de 5 dias! Ganhe 2x XP nas próximas 2 horas', icon: '⚡', read: false, createdAt: '13 abr 07:30' },
  { id: 'n19', type: 'system', title: 'Atualização disponível', message: 'Nova versão do NEXA com melhorias de performance', icon: '🆕', read: true, createdAt: '11 abr 14:00' },
  { id: 'n20', type: 'bet_result', title: 'Aposta GREEN!', message: 'Flamengo 3x1 Boca - Você ganhou R$ 28,00', icon: '✅', read: true, createdAt: '11 abr 23:30' },
  { id: 'n21', type: 'season', title: 'Ranking atualizado', message: 'Você subiu para a posição #42 no ranking geral', icon: '📈', read: false, createdAt: '13 abr 05:00' },
];
